# permissions for end users to edit notebooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: notebook-editor-role
rules:
- apiGroups:
  - notebook.zoracloud.ai
  resources:
  - notebooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - notebook.zoracloud.ai
  resources:
  - notebooks/status
  verbs:
  - get
