apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixy
  namespace: kafka
  labels:
    app: pixy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pixy
  template:
    metadata:
      labels:
        app: pixy
    spec:
      containers:
      - name: pixy
        image: mailgun/kafka-pixy
        ports:
        - containerPort: 80
        command:
        - kafka-pixy
        - -kafkaPeers
        - zora-kafka-brokers.kafka.svc.cluster.local:9092
        - -zookeeperPeers
        - zora-zookeeper-client.kafka.svc.cluster.local:2181
        - -tcpAddr
        - 0.0.0.0:80
        - -grpcAddr
        - 0.0.0.0:9090
        - -config
        - config/kafka-pixy.yaml